[package]
name = "xifty-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "xifty_cli"

[dependencies]
clap.workspace = true
flate2.workspace = true
serde_json.workspace = true
xifty-core = { path = "../xifty-core" }
xifty-detect = { path = "../xifty-detect" }
xifty-source = { path = "../xifty-source" }
xifty-container-jpeg = { path = "../xifty-container-jpeg" }
xifty-container-tiff = { path = "../xifty-container-tiff" }
xifty-container-png = { path = "../xifty-container-png" }
xifty-container-riff = { path = "../xifty-container-riff" }
xifty-container-isobmff = { path = "../xifty-container-isobmff" }
xifty-container-flac = { path = "../xifty-container-flac" }
xifty-container-ogg = { path = "../xifty-container-ogg" }
xifty-container-aiff = { path = "../xifty-container-aiff" }
xifty-container-id3 = { path = "../xifty-container-id3" }
xifty-container-gif = { path = "../xifty-container-gif" }
xifty-container-raf = { path = "../xifty-container-raf" }
xifty-container-rw2 = { path = "../xifty-container-rw2" }
xifty-meta-exif = { path = "../xifty-meta-exif" }
xifty-meta-icc = { path = "../xifty-meta-icc" }
xifty-meta-iptc = { path = "../xifty-meta-iptc" }
xifty-meta-id3v2 = { path = "../xifty-meta-id3v2" }
xifty-meta-apple = { path = "../xifty-meta-apple" }
xifty-meta-bwf = { path = "../xifty-meta-bwf" }
xifty-meta-ixml = { path = "../xifty-meta-ixml" }
xifty-meta-sony = { path = "../xifty-meta-sony" }
xifty-meta-sony-video = { path = "../xifty-meta-sony-video" }
xifty-meta-nikon = { path = "../xifty-meta-nikon" }
xifty-meta-olympus = { path = "../xifty-meta-olympus" }
xifty-meta-canon = { path = "../xifty-meta-canon" }
xifty-meta-fuji = { path = "../xifty-meta-fuji" }
xifty-meta-panasonic = { path = "../xifty-meta-panasonic" }
xifty-meta-xmp = { path = "../xifty-meta-xmp" }
xifty-meta-quicktime = { path = "../xifty-meta-quicktime" }
xifty-meta-itunes = { path = "../xifty-meta-itunes" }
xifty-meta-rtmd = { path = "../xifty-meta-rtmd" }
xifty-meta-vorbis-comment = { path = "../xifty-meta-vorbis-comment" }
xifty-normalize = { path = "../xifty-normalize" }
xifty-policy = { path = "../xifty-policy" }
xifty-sidecar = { path = "../xifty-sidecar" }
xifty-sidecar-sony-nrt = { path = "../xifty-sidecar-sony-nrt" }
xifty-validate = { path = "../xifty-validate" }
xifty-json = { path = "../xifty-json" }

[dev-dependencies]
insta.workspace = true
serde_json.workspace = true
